# Generated by Django 5.1.1 on 2025-01-30 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('letter', models.CharField(max_length=1)),
                ('isactive', models.BooleanField(default=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('createdby', models.CharField(max_length=128)),
                ('modifiedby', models.CharField(blank=True, max_length=128)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Classes',
                'verbose_name_plural': 'Classes',
                'db_table': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('createdby', models.CharField(max_length=128)),
                ('modifiedby', models.CharField(blank=True, max_length=128)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Gender',
                'db_table': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('surname', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('createdby', models.CharField(max_length=128)),
                ('modifiedby', models.CharField(blank=True, max_length=128)),
                ('isdeleted', models.BooleanField()),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Parents',
                'verbose_name_plural': 'Parents',
                'db_table': 'Parents',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('createdby', models.CharField(max_length=128)),
                ('modifiedby', models.CharField(blank=True, max_length=128)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payment',
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('surname', models.CharField(blank=True, max_length=128)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('createdby', models.CharField(max_length=128)),
                ('modifiedby', models.CharField(blank=True, max_length=128)),
                ('isdeleted', models.BooleanField(max_length=128)),
            ],
            options={
                'verbose_name': 'Teachers',
                'verbose_name_plural': 'Teachers',
                'db_table': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Pupils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('surname', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(choices=[('Мальчик', 'Мальчик'), ('Девочка', 'Девочка')], max_length=10)),
                ('birthday', models.DateField()),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('createdby', models.CharField(max_length=128)),
                ('modifiedby', models.CharField(blank=True, max_length=128)),
                ('isdeleted', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.classes')),
            ],
            options={
                'verbose_name': 'Pupils',
                'verbose_name_plural': 'Pupils',
                'db_table': 'Pupils',
            },
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.teachers'),
        ),
        migrations.CreateModel(
            name='ParentPupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.parents', verbose_name='Parent')),
                ('pupil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.pupils', verbose_name='Child')),
            ],
            options={
                'verbose_name': 'Parents And Pupils',
                'verbose_name_plural': 'Parents And Pupils',
                'db_table': 'Parents And Pupils',
                'unique_together': {('parent', 'pupil')},
            },
        ),
    ]
