# Generated by Django 5.1.1 on 2025-01-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentpupil',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.parents', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='parentpupil',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.pupils', verbose_name='Child'),
        ),
    ]
