# Generated by Django 5.1.1 on 2024-12-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_alter_parents_phone_alter_pupils_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='createdby',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='classes',
            name='modifiedby',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
    ]
