# Generated by Django 5.1.1 on 2024-12-23 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_alter_classes_createdby_alter_classes_modifiedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentpupil',
            name='createdby',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentpupil',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentpupil',
            name='modifiedby',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='parentpupil',
            name='modifiedon',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
